# Untransfected_AngII_Analysis

In [1]:
pip install xlrd

Requirement already satisfied: xlrd in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from numpy import float64, subtract, divide

In [4]:
def convert_rep(row):
    row['rep'] = row['Sample Name'][-1]
    row['Sample Name'] = row['Sample Name'][:len(row['Sample Name']) - 5]
    return row

In [5]:
rawDataSet_2 = pd.read_excel(r'/Users/sanas/Projects/molecule-54/AngII-stim/resources/AngII_rep2.xlsx', sheet_name = 'Results', header = 50, decimal = ",")
rawDataSet_3and4 = pd.read_excel(r'/Users/sanas/Projects/molecule-54/AngII-stim/resources/AngII_rep3-rep4.xls', sheet_name = 'Results', header = 50, decimal = ",")
rawDataSet_5and6 = pd.read_excel(r'/Users/sanas/Projects/molecule-54/AngII-stim/resources/AngII_rep5-rep6.xls', sheet_name = 'Results', header = 50, decimal = ",")


AngII_clean_2 = rawDataSet_2.drop(columns = ['Well', 'Well Position', 'Omit', 'Task', 'Reporter', 'Quencher', 'Quantity', \
                                    'Quantity Mean', 'Quantity SD', 'RQ', 'RQ Min', 'RQ Max', 'Delta Ct', 'Delta Ct Mean', \
                                     'Delta Ct SD', 'Delta Ct SE', 'Delta Delta Ct', 'Automatic Ct Threshold', \
                                     'Ct Threshold', 'Automatic Baseline', 'Baseline Start', \
                                    'Baseline End', 'Amp Status', 'Comments', 'Cq Conf', 'CQCONF', 'EXPFAIL', 'NOAMP', 'HIGHSD'])

AngII_clean_2['rep'] = '2'
AngII_clean_2 = AngII_clean_2[AngII_clean_2['Sample Name'].str.contains('rep')== False ]
AngII_wo_na_2 = AngII_clean_2.dropna(axis = 0)
AngII_wo_na_2

       Sample Name Target Name         CT    Ct Mean     Ct SD rep
36   Untransfected       GAPDH  28.776197  28.775597  0.000850   2
37   Untransfected       GAPDH  28.774996  28.775597  0.000850   2
38           AngII       GAPDH  28.257355  28.042526  0.303812   2
39           AngII       GAPDH    27.8277  28.042526  0.303812   2
40  AngII + mol-54       GAPDH  28.284531  28.189013  0.135083   2
41  AngII + mol-54       GAPDH  28.093494  28.189013  0.135083   2
42   Untransfected     CYP11B2  34.982246  34.775848  0.291888   2
43   Untransfected     CYP11B2  34.569454  34.775848  0.291888   2
44           AngII     CYP11B2    27.3069  27.335764  0.040820   2
45           AngII     CYP11B2  27.364628  27.335764  0.040820   2
46  AngII + mol-54     CYP11B2  28.065977  28.031193  0.049194   2
47  AngII + mol-54     CYP11B2  27.996407  28.031193  0.049194   2

In [6]:
AngII_clean_3and4 = rawDataSet_3and4.drop(columns = ['Well', 'Well Position', 'Omit', 'Task', 'Reporter', 'Quencher', 'Quantity', \
                                    'Quantity Mean', 'Quantity SD', 'RQ', 'RQ Min', 'RQ Max', 'Delta Ct', 'Delta Ct Mean', \
                                     'Delta Ct SD', 'Delta Ct SE', 'Delta Delta Ct', 'Automatic Ct Threshold', \
                                     'Ct Threshold', 'Automatic Baseline', 'Baseline Start', \
                                    'Baseline End', 'Amp Status', 'Comments', 'Cq Conf', 'CQCONF', 'EXPFAIL', 'NOAMP',])

AngII_clean_3and4 = AngII_clean_3and4.dropna(axis = 0)
AngII_clean_3and4 = AngII_clean_3and4[AngII_clean_3and4['Sample Name'].str.contains('rep')]
AngII_clean_3and4 = AngII_clean_3and4.apply(convert_rep, axis = 1)

AngII_clean_3and4

       Sample Name Target Name         CT    Ct Mean     Ct SD rep
0        Untreated       GAPDH  26.233788  26.120548  0.160143   3
1        Untreated       GAPDH  26.007311  26.120548  0.160143   3
2            AngII       GAPDH  25.752451  25.775509  0.032607   3
3            AngII       GAPDH  25.798565  25.775509  0.032607   3
4   AngII + mol-54       GAPDH  25.821255  25.801086  0.028524   3
5   AngII + mol-54       GAPDH  25.780916  25.801086  0.028524   3
6        Untreated       GAPDH  25.808231  25.875061  0.094513   4
7        Untreated       GAPDH  25.941893  25.875061  0.094513   4
8            AngII       GAPDH  26.090498  26.234150  0.203156   4
9            AngII       GAPDH  26.377804  26.234150  0.203156   4
10  AngII + mol-54       GAPDH  26.282017  26.163921  0.167013   4
11  AngII + mol-54       GAPDH  26.045824  26.163921  0.167013   4
12       Untreated     CYP11B2  31.099165  31.104525  0.007580   3
13       Untreated     CYP11B2  31.109884  31.104525  0.007580   3
14           AngII     CYP11B2  25.060875  25.130394  0.098316   3
15           AngII     CYP11B2  25.199915  25.130394  0.098316   3
16  AngII + mol-54     CYP11B2  25.842903  25.985344  0.201440   3
17       Untreated     CYP11B2  32.022354  31.857391  0.233294   4
18       Untreated     CYP11B2  31.692427  31.857391  0.233294   4
19           AngII     CYP11B2  25.844683  25.812138  0.046024   4
20           AngII     CYP11B2  25.779594  25.812138  0.046024   4
21  AngII + mol-54     CYP11B2  26.671593  26.825146  0.217158   4
22  AngII + mol-54     CYP11B2  26.978701  26.825146  0.217158   4
23  AngII + mol-54     CYP11B2  26.127783  25.985344  0.201440   3

In [7]:
AngII_clean_5and6 = rawDataSet_5and6.drop(columns = ['Well', 'Well Position', 'Omit', 'Task', 'Reporter', 'Quencher', 'Quantity', \
                                    'Quantity Mean', 'Quantity SD', 'RQ', 'RQ Min', 'RQ Max', 'Delta Ct', 'Delta Ct Mean', \
                                     'Delta Ct SD', 'Delta Ct SE', 'Delta Delta Ct', 'Automatic Ct Threshold', \
                                     'Ct Threshold', 'Automatic Baseline', 'Baseline Start', \
                                    'Baseline End', 'Amp Status', 'Comments', 'Cq Conf', 'CQCONF', 'EXPFAIL']) 

AngII_clean_5and6 = AngII_clean_5and6.dropna(axis = 0)
AngII_clean_5and6 = AngII_clean_5and6[AngII_clean_5and6['Sample Name'].str.contains('rep')]
AngII_clean_5and6 = AngII_clean_5and6.apply(convert_rep, axis = 1)

AngII_clean_5and6

       Sample Name Target Name         CT    Ct Mean     Ct SD rep
0        Untreated       GAPDH  26.276197  25.926300  0.494828   5
1        Untreated       GAPDH  25.576405  25.926300  0.494828   5
2            AngII       GAPDH  24.931860  25.112541  0.255523   5
3            AngII       GAPDH  25.293224  25.112541  0.255523   5
4     AngII + m-54       GAPDH  24.767658  24.795723  0.039690   5
5     AngII + m-54       GAPDH  24.823788  24.795723  0.039690   5
6        Untreated       GAPDH  25.230234  25.346279  0.164111   6
7        Untreated       GAPDH  25.462322  25.346279  0.164111   6
8            AngII       GAPDH  25.285358  25.346550  0.086538   6
9            AngII       GAPDH  25.407742  25.346550  0.086538   6
10  AngII + mol-54       GAPDH  25.356382  25.558651  0.286052   6
11  AngII + mol-54       GAPDH  25.760921  25.558651  0.286052   6
12       Untreated     CYP11B2  32.204502  32.341404  0.193608   5
13       Untreated     CYP11B2  32.478306  32.341404  0.193608   5
14           AngII     CYP11B2  25.789160  25.824665  0.050212   5
15           AngII     CYP11B2  25.860170  25.824665  0.050212   5
16    AngII + m-54     CYP11B2  26.688368  26.721720  0.047167   5
17    AngII + m-54     CYP11B2  26.755072  26.721720  0.047167   5
18       Untreated     CYP11B2  31.974920  31.969683  0.007407   6
19       Untreated     CYP11B2  31.964445  31.969683  0.007407   6
20           AngII     CYP11B2  25.974489  26.047600  0.103394   6
21           AngII     CYP11B2  26.120710  26.047600  0.103394   6
22  AngII + mol-54     CYP11B2  28.050341  28.118612  0.096551   6
23  AngII + mol-54     CYP11B2  28.186884  28.118612  0.096551   6

In [58]:
mergedAngII = pd.concat([AngII_wo_na_2, AngII_clean_3and4, AngII_clean_5and6]).replace('Untransfected', 'Untreated', regex = True).replace('mol-54', 'm-54', regex = True)
mergedAngII

     Sample Name Target Name         CT    Ct Mean     Ct SD rep
36     Untreated       GAPDH  28.776197  28.775597  0.000850   2
37     Untreated       GAPDH  28.774996  28.775597  0.000850   2
38         AngII       GAPDH  28.257355  28.042526  0.303812   2
39         AngII       GAPDH  27.827700  28.042526  0.303812   2
40  AngII + m-54       GAPDH  28.284531  28.189013  0.135083   2
41  AngII + m-54       GAPDH  28.093494  28.189013  0.135083   2
42     Untreated     CYP11B2  34.982246  34.775848  0.291888   2
43     Untreated     CYP11B2  34.569454  34.775848  0.291888   2
44         AngII     CYP11B2  27.306900  27.335764  0.040820   2
45         AngII     CYP11B2  27.364628  27.335764  0.040820   2
46  AngII + m-54     CYP11B2  28.065977  28.031193  0.049194   2
47  AngII + m-54     CYP11B2  27.996407  28.031193  0.049194   2
0      Untreated       GAPDH  26.233788  26.120548  0.160143   3
1      Untreated       GAPDH  26.007311  26.120548  0.160143   3
2          AngII       GAPDH  25.752451  25.775509  0.032607   3
3          AngII       GAPDH  25.798565  25.775509  0.032607   3
4   AngII + m-54       GAPDH  25.821255  25.801086  0.028524   3
5   AngII + m-54       GAPDH  25.780916  25.801086  0.028524   3
6      Untreated       GAPDH  25.808231  25.875061  0.094513   4
7      Untreated       GAPDH  25.941893  25.875061  0.094513   4
8          AngII       GAPDH  26.090498  26.234150  0.203156   4
9          AngII       GAPDH  26.377804  26.234150  0.203156   4
10  AngII + m-54       GAPDH  26.282017  26.163921  0.167013   4
11  AngII + m-54       GAPDH  26.045824  26.163921  0.167013   4
12     Untreated     CYP11B2  31.099165  31.104525  0.007580   3
13     Untreated     CYP11B2  31.109884  31.104525  0.007580   3
14         AngII     CYP11B2  25.060875  25.130394  0.098316   3
15         AngII     CYP11B2  25.199915  25.130394  0.098316   3
16  AngII + m-54     CYP11B2  25.842903  25.985344  0.201440   3
17     Untreated     CYP11B2  32.022354  31.857391  0.233294   4
18     Untreated     CYP11B2  31.692427  31.857391  0.233294   4
19         AngII     CYP11B2  25.844683  25.812138  0.046024   4
20         AngII     CYP11B2  25.779594  25.812138  0.046024   4
21  AngII + m-54     CYP11B2  26.671593  26.825146  0.217158   4
22  AngII + m-54     CYP11B2  26.978701  26.825146  0.217158   4
23  AngII + m-54     CYP11B2  26.127783  25.985344  0.201440   3
0      Untreated       GAPDH  26.276197  25.926300  0.494828   5
1      Untreated       GAPDH  25.576405  25.926300  0.494828   5
2          AngII       GAPDH  24.931860  25.112541  0.255523   5
3          AngII       GAPDH  25.293224  25.112541  0.255523   5
4   AngII + m-54       GAPDH  24.767658  24.795723  0.039690   5
5   AngII + m-54       GAPDH  24.823788  24.795723  0.039690   5
6      Untreated       GAPDH  25.230234  25.346279  0.164111   6
7      Untreated       GAPDH  25.462322  25.346279  0.164111   6
8          AngII       GAPDH  25.285358  25.346550  0.086538   6
9          AngII       GAPDH  25.407742  25.346550  0.086538   6
10  AngII + m-54       GAPDH  25.356382  25.558651  0.286052   6
11  AngII + m-54       GAPDH  25.760921  25.558651  0.286052   6
12     Untreated     CYP11B2  32.204502  32.341404  0.193608   5
13     Untreated     CYP11B2  32.478306  32.341404  0.193608   5
14         AngII     CYP11B2  25.789160  25.824665  0.050212   5
15         AngII     CYP11B2  25.860170  25.824665  0.050212   5
16  AngII + m-54     CYP11B2  26.688368  26.721720  0.047167   5
17  AngII + m-54     CYP11B2  26.755072  26.721720  0.047167   5
18     Untreated     CYP11B2  31.974920  31.969683  0.007407   6
19     Untreated     CYP11B2  31.964445  31.969683  0.007407   6
20         AngII     CYP11B2  25.974489  26.047600  0.103394   6
21         AngII     CYP11B2  26.120710  26.047600  0.103394   6
22  AngII + m-54     CYP11B2  28.050341  28.118612  0.096551   6
23  AngII + m-54     CYP11B2  28.186884  28.118612  0.096551   6

In [59]:
AngII_data_dedupl = mergedAngII.drop(columns=['CT', 'Ct SD']).drop_duplicates()
AngII_data_dedupl

     Sample Name Target Name    Ct Mean rep
36     Untreated       GAPDH  28.775597   2
38         AngII       GAPDH  28.042526   2
40  AngII + m-54       GAPDH  28.189013   2
42     Untreated     CYP11B2  34.775848   2
44         AngII     CYP11B2  27.335764   2
46  AngII + m-54     CYP11B2  28.031193   2
0      Untreated       GAPDH  26.120548   3
2          AngII       GAPDH  25.775509   3
4   AngII + m-54       GAPDH  25.801086   3
6      Untreated       GAPDH  25.875061   4
8          AngII       GAPDH  26.234150   4
10  AngII + m-54       GAPDH  26.163921   4
12     Untreated     CYP11B2  31.104525   3
14         AngII     CYP11B2  25.130394   3
16  AngII + m-54     CYP11B2  25.985344   3
17     Untreated     CYP11B2  31.857391   4
19         AngII     CYP11B2  25.812138   4
21  AngII + m-54     CYP11B2  26.825146   4
0      Untreated       GAPDH  25.926300   5
2          AngII       GAPDH  25.112541   5
4   AngII + m-54       GAPDH  24.795723   5
6      Untreated       GAPDH  25.346279   6
8          AngII       GAPDH  25.346550   6
10  AngII + m-54       GAPDH  25.558651   6
12     Untreated     CYP11B2  32.341404   5
14         AngII     CYP11B2  25.824665   5
16  AngII + m-54     CYP11B2  26.721720   5
18     Untreated     CYP11B2  31.969683   6
20         AngII     CYP11B2  26.047600   6
22  AngII + m-54     CYP11B2  28.118612   6

In [60]:
CYP11B2_values = AngII_data_dedupl[AngII_data_dedupl['Target Name'] == 'CYP11B2']

def delta_CT(CYP11B2_value):
    GAPDH_value = AngII_data_dedupl[(AngII_data_dedupl['Target Name'] == 'GAPDH') &
                                    (AngII_data_dedupl['Sample Name'] == CYP11B2_value['Sample Name']) &
                                    (AngII_data_dedupl['rep'] == CYP11B2_value['rep'])
                                  ]
    CYP11B2_value['GAPDH'] = float64(GAPDH_value['Ct Mean'])
    CYP11B2_value['Delta CT'] = float64(subtract(CYP11B2_value['Ct Mean'], GAPDH_value['Ct Mean']))   
    
    return CYP11B2_value

deltaCT_CYP11B2 = CYP11B2_values.apply(delta_CT, axis = 1).drop(columns = ['Target Name', 'GAPDH'])
deltaCT_CYP11B2

     Sample Name    Ct Mean rep  Delta CT
42     Untreated  34.775848   2  6.000252
44         AngII  27.335764   2 -0.706762
46  AngII + m-54  28.031193   2 -0.157820
12     Untreated  31.104525   3  4.983976
14         AngII  25.130394   3 -0.645115
16  AngII + m-54  25.985344   3  0.184258
17     Untreated  31.857391   4  5.982330
19         AngII  25.812138   4 -0.422012
21  AngII + m-54  26.825146   4  0.661224
12     Untreated  32.341404   5  6.415104
14         AngII  25.824665   5  0.712124
16  AngII + m-54  26.721720   5  1.925997
18     Untreated  31.969683   6  6.623404
20         AngII  26.047600   6  0.701050
22  AngII + m-54  28.118612   6  2.559961

In [61]:
doubleDeltaCT_CYP11B2 = 2 ** (-deltaCT_CYP11B2['Delta CT'])
float64(doubleDeltaCT_CYP11B2)

array([0.01562227, 1.63213717, 1.11559993, 0.03159902, 1.56386383,
       0.88010191, 0.01581755, 1.33979505, 0.63234142, 0.01171821,
       0.61042084, 0.26315838, 0.01014278, 0.61512444, 0.16958009])

In [63]:
deltaCT_CYP11B2['Double Delta CT'] = doubleDeltaCT_CYP11B2
deltaCT_CYP11B2

     Sample Name    Ct Mean rep  Delta CT  Double Delta CT
42     Untreated  34.775848   2  6.000252         0.015622
44         AngII  27.335764   2 -0.706762         1.632137
46  AngII + m-54  28.031193   2 -0.157820         1.115600
12     Untreated  31.104525   3  4.983976         0.031599
14         AngII  25.130394   3 -0.645115         1.563864
16  AngII + m-54  25.985344   3  0.184258         0.880102
17     Untreated  31.857391   4  5.982330         0.015818
19         AngII  25.812138   4 -0.422012         1.339795
21  AngII + m-54  26.825146   4  0.661224         0.632341
12     Untreated  32.341404   5  6.415104         0.011718
14         AngII  25.824665   5  0.712124         0.610421
16  AngII + m-54  26.721720   5  1.925997         0.263158
18     Untreated  31.969683   6  6.623404         0.010143
20         AngII  26.047600   6  0.701050         0.615124
22  AngII + m-54  28.118612   6  2.559961         0.169580

In [64]:
#untreated_rep2 = deltaCT_CYP11B2[(deltaCT_CYP11B2['Sample Name'] == 'Untreated') &
                                 #(deltaCT_CYP11B2['rep'] == '2')
                                #]

#untreated_rep2['Double Delta CT']

def extract_untreated (browsed_dataframe):
    untreated = browsed_dataframe[(browsed_dataframe['Sample Name'] == 'Untreated') &
                          (browsed_dataframe['rep'] == browsed_dataframe['rep'])
                         ]
    return untreated

untreated_per_rep = extract_untreated(deltaCT_CYP11B2)
untreated_per_rep

   Sample Name    Ct Mean rep  Delta CT  Double Delta CT
42   Untreated  34.775848   2  6.000252         0.015622
12   Untreated  31.104525   3  4.983976         0.031599
17   Untreated  31.857391   4  5.982330         0.015818
12   Untreated  32.341404   5  6.415104         0.011718
18   Untreated  31.969683   6  6.623404         0.010143

In [65]:
def extract_angII (browsed_dataframe):
    angII = browsed_dataframe[(browsed_dataframe['Sample Name'] == 'AngII') &
                          (browsed_dataframe['rep'] == browsed_dataframe['rep'])
                         ]
    return angII

angII_per_rep = extract_angII(deltaCT_CYP11B2)
angII_per_rep

   Sample Name    Ct Mean rep  Delta CT  Double Delta CT
44       AngII  27.335764   2 -0.706762         1.632137
14       AngII  25.130394   3 -0.645115         1.563864
19       AngII  25.812138   4 -0.422012         1.339795
14       AngII  25.824665   5  0.712124         0.610421
20       AngII  26.047600   6  0.701050         0.615124

In [66]:
def extract_angII_m54 (browsed_dataframe):
    angII_m54 = browsed_dataframe[(browsed_dataframe['Sample Name'] == 'AngII + m-54') &
                          (browsed_dataframe['rep'] == browsed_dataframe['rep'])
                         ]
    return angII_m54

angII_m54_per_rep = extract_angII_m54(deltaCT_CYP11B2)
angII_m54_per_rep

     Sample Name    Ct Mean rep  Delta CT  Double Delta CT
46  AngII + m-54  28.031193   2 -0.157820         1.115600
16  AngII + m-54  25.985344   3  0.184258         0.880102
21  AngII + m-54  26.825146   4  0.661224         0.632341
16  AngII + m-54  26.721720   5  1.925997         0.263158
22  AngII + m-54  28.118612   6  2.559961         0.169580

In [71]:
foldChange_angII = divide(angII_per_rep['Double Delta CT'], untreated_per_rep['Double Delta CT'])
foldChange_angII

12   NaN
12   NaN
14   NaN
14   NaN
17   NaN
18   NaN
19   NaN
20   NaN
42   NaN
44   NaN
Name: Double Delta CT, dtype: float64

In [ ]:
untreated_rep2 = deltaCT_CYP11B2[deltaCT_CYP11B2['rep'] == '2']

untreated_rep3 = deltaCT_CYP11B2[deltaCT_CYP11B2['rep'] == '3']

untreated_rep4 = deltaCT_CYP11B2[deltaCT_CYP11B2['rep'] == '4']

untreated_rep5 = deltaCT_CYP11B2[deltaCT_CYP11B2['rep'] == '5']

untreated_rep6 = deltaCT_CYP11B2[deltaCT_CYP11B2['rep'] == '6']

def foldChange(rep_data_frame):
    untreated = rep_data_frame[rep_data_frame['Sample Name'] == 'Untreated']['Double Delta CT']
    angII = rep_data_frame[rep_data_frame['Sample Name'] == 'AngII']['Double Delta CT']
    angII_m54 = rep_data_frame[rep_data_frame['Sample Name'] == 'AngII + mol-54']['Double Delta CT']
    
    foldChange_AngII = float64(untreated / angII)
    foldChange_AngII_m54 = float64(untreated / angII_m54)
    
    return [1, foldChange_AngII, foldChange_AngII_m54]

    #print(divide(angII, angII_m54))
    
    #return [1, foldChange_angII, foldChange_angII_m54]
    
untreated_rep2 = foldChange(untreated_rep2)
#untreated_rep2['Fold Change'] = foldChange(untreated_rep2)
#untreated_rep3['Fold Change'] = foldChange(untreated_rep3)
#untreated_rep4['Fold Change'] = foldChange(untreated_rep4)
#untreated_rep5['Fold Change'] = foldChange(untreated_rep5)
#untreated_rep6['Fold Change'] = foldChange(untreated_rep6)
#combined = pd.concat([untreated_rep2, untreated_rep3, untreated_rep4, untreated_rep5, untreated_rep6])

#deltaCT_CYP11B2['Fold Change'] = combined
#deltaCT_CYP11B2

untreated_rep2